disabled_rules: 
  - line_length
  - function_parameter_count
  - todo
included: 
  - AirCanadaMobile 
opt_in_rules:
   - operator_usage_whitespace

# configurable rules can be customized from this configuration file
# binary rules can set their severity level
identifier_name:
  max_length:
    warning: 50
    error: 60
  excluded:
    - y
    - up

type_name:
  max_length:
    warning: 50
    error: 60

large_tuple:
  - 3
  - 4
